name: adhoc-proxy
services:
  service:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NGINX_FROM_IMAGE: nginx:1.25.4
        ENABLED_MODULES: ndk lua
      tags:
        - farcsal/adhoc-proxy:latest
    restart: no
    environment:
      - UPSTREAM_SERVER=http://example.com
      - IDLE_TIMEOUT_SECONDS=300
    volumes:
      - ./certificate.crt:/etc/nginx/certificate.crt
      - ./privatekey.key:/etc/nginx/privatekey.key
    ports:
      - 8443:443
